server:
  port: 0
  shutdown: graceful

log:
  dir: user-auth

redis:
  database:
    index: 8

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: User Authentication Service
    description: This service is responsible for authenticate users.
    version: 1.0

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 3

spring:
  profiles:
    active: dev
  application:
    name: user-auth-service
  lifecycle:
    timeout-per-shutdown-phase: "90s"
  datasource:
    hikari:
      maximum-pool-size: 9
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  token:
    prefix: Bearer

http:
  header:
    current:
      context: CurrentContext
    language: Accept-Language

springdoc:
  paths-to-exclude: /swagger-resources/**, /v3/api-docs/**, /v2/api-docs/**

user:
  identity:
    regexList:
      - ^\d{11}$
      - ^\d{4}$