server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import:
      - kafka-dev.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?currentSchema=user
    username: postgres
    password: root


redis:
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    max:
      connection: 30
      idle:
        connection: 10
    min:
      idle:
        connection: 0

jwt:
  token:
    expiry:
      minute: 360
  secret:
    key: 327234753778214125442A472D4B6150645367566B59703373367638792F423F

password:
  strength: 11

feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 200
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 60000
        requestIntreceptors:
          - com.ecommerce.userauth.rest.interceptor.FeignClientRequestInterceptor

logging:
  config: classpath:log/logback-dev.xml

two:
  factor:
    auth:
      feign: real


otp:
  expiry:
    minutes: 2

service:
  core:
    impl: real

user:
  password:
    length: 4

  temporary-password:
    validity:
      minutes: 60

encryption:
  secret:
    key: SHAJ@pocket@123
